name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install WebSharper templates
        run: dotnet new -i WebSharper.Templates

      - name:- name: Build project
  run: |
    dotnet build AdhdFocusTimer.sln
    dotnet publish AdhdFocusTimer.Client/AdhdFocusTimer.Client.fsproj -c Release -o output


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/wwwroot

